package npm

import (
	"testing"

	"ihbv.io/depsnort/internal/graph"
	"ihbv.io/depsnort/internal/purl"
)

// A Yarn v1 (classic) lockfile: quoted descriptors, space-separated fields,
// bare ranges. chalk depends on ansi-styles; the root (from package.json)
// depends on chalk.
const yarnV1 = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


chalk@^5.3.0:
  version "5.3.0"
  resolved "https://registry.yarnpkg.com/chalk/-/chalk-5.3.0.tgz#abc"
  integrity sha512-deadbeef
  dependencies:
    ansi-styles "^6.2.1"

"ansi-styles@^6.2.1":
  version "6.2.1"
  resolved "https://registry.yarnpkg.com/ansi-styles/-/ansi-styles-6.2.1.tgz#def"
  integrity sha512-cafebabe

left-pad@^1.3.0:
  version "1.3.0"
  resolved "https://registry.yarnpkg.com/left-pad/-/left-pad-1.3.0.tgz#ghi"
  integrity sha512-01234567
`

const yarnManifest = `{
  "name": "myapp",
  "version": "1.2.3",
  "dependencies": { "chalk": "^5.3.0" },
  "devDependencies": { "left-pad": "^1.3.0" }
}`

func TestParseYarnV1(t *testing.T) {
	g, err := parseYarnLock([]byte(yarnV1), []byte(yarnManifest), "/tmp/myapp")
	if err != nil {
		t.Fatal(err)
	}
	for _, n := range g.SortedNodes() {
		t.Logf("d%d %-34s direct=%v src=%s", n.Depth, n.ID, n.Direct, srcClass(n))
	}

	if len(g.Roots) != 1 || g.Roots[0] != "pkg:npm/myapp@1.2.3" {
		t.Fatalf("roots = %v, want [pkg:npm/myapp@1.2.3]", g.Roots)
	}

	// chalk is a direct (runtime) dep at depth 1; left-pad is a direct devDep the
	// root installs, also depth 1; ansi-styles is transitive at depth 2.
	chalk := g.Get("pkg:npm/chalk@5.3.0")
	if chalk == nil || !chalk.Direct || chalk.Depth != 1 {
		t.Errorf("chalk wrong: %+v", chalk)
	}
	leftpad := g.Get("pkg:npm/left-pad@1.3.0")
	if leftpad == nil || !leftpad.Direct || leftpad.Depth != 1 {
		t.Errorf("left-pad (devDep) wrong: %+v", leftpad)
	}
	ansi := g.Get("pkg:npm/ansi-styles@6.2.1")
	if ansi == nil {
		t.Fatal("transitive ansi-styles missing")
	}
	if ansi.Direct {
		t.Error("ansi-styles is transitive, not direct")
	}
	if ansi.Depth != 2 {
		t.Errorf("ansi-styles depth = %d, want 2 (root->chalk->ansi-styles)", ansi.Depth)
	}

	// The chalk -> ansi-styles edge must exist (descriptor "ansi-styles@^6.2.1"
	// resolved to the ansi-styles@6.2.1 node).
	if !hasEdge(g, "pkg:npm/chalk@5.3.0", "pkg:npm/ansi-styles@6.2.1") {
		t.Error("missing edge chalk -> ansi-styles")
	}
	// Registry origin classified from the resolved URL.
	if srcClass(ansi) != graph.SourceRegistry {
		t.Errorf("ansi-styles source = %q, want registry", srcClass(ansi))
	}
}

// A Yarn v2+ (berry) lockfile: YAML colons, descriptors joined in one quoted
// string, "npm:" range protocol, scoped names.
const yarnBerry = `# This file is generated by running "yarn install" inside your project.

"@scope/ui@npm:^1.0.0":
  version: 1.4.2
  resolution: "@scope/ui@npm:1.4.2"
  dependencies:
    tslib: "npm:^2.6.0"
  checksum: 10c0/abc
  languageName: node
  linkType: hard

"tslib@npm:^2.6.0, tslib@npm:^2.6.2":
  version: 2.6.2
  resolution: "tslib@npm:2.6.2"
  checksum: 10c0/def
  languageName: node
  linkType: hard
`

const berryManifest = `{
  "name": "berry-app",
  "version": "0.1.0",
  "dependencies": { "@scope/ui": "^1.0.0" }
}`

func TestParseYarnBerry(t *testing.T) {
	g, err := parseYarnLock([]byte(yarnBerry), []byte(berryManifest), "/tmp/berry-app")
	if err != nil {
		t.Fatal(err)
	}
	for _, n := range g.SortedNodes() {
		t.Logf("d%d %-30s direct=%v", n.Depth, n.ID, n.Direct)
	}
	uiID := purl.NewNpm("@scope/ui", "1.4.2").String() // scope '@' is %40-encoded
	tslibID := purl.NewNpm("tslib", "2.6.2").String()
	ui := g.Get(uiID)
	if ui == nil || !ui.Direct || ui.Depth != 1 {
		t.Errorf("@scope/ui wrong: %+v", ui)
	}
	tslib := g.Get(tslibID)
	if tslib == nil {
		t.Fatal("tslib missing")
	}
	if tslib.Depth != 2 {
		t.Errorf("tslib depth = %d, want 2", tslib.Depth)
	}
	// The berry "npm:" protocol on both the descriptor and the dep reference must
	// normalize so the edge lands.
	if !hasEdge(g, uiID, tslibID) {
		t.Error("missing edge @scope/ui -> tslib (npm: protocol not normalized)")
	}
}

// Without a package.json, the root is synthesized and anchored on the packages
// nothing depends on (in-degree 0), so the tree still ladders.
func TestParseYarnNoManifestAnchorsOnTopology(t *testing.T) {
	g, err := parseYarnLock([]byte(yarnV1), nil, "/tmp/proj")
	if err != nil {
		t.Fatal(err)
	}
	if len(g.Roots) != 1 {
		t.Fatalf("roots = %v, want one synthesized root", g.Roots)
	}
	// chalk and left-pad are in-degree 0 (nothing requires them); ansi-styles is
	// required by chalk. So chalk and left-pad anchor at depth 1, ansi at depth 2.
	if n := g.Get("pkg:npm/ansi-styles@6.2.1"); n == nil || n.Depth != 2 {
		t.Errorf("ansi-styles should ladder to depth 2, got %+v", n)
	}
	if n := g.Get("pkg:npm/chalk@5.3.0"); n == nil || n.Depth != 1 {
		t.Errorf("chalk should anchor at depth 1, got %+v", n)
	}
}

func srcClass(n *graph.Node) string {
	c, _ := n.SourceOf()
	return c
}

func hasEdge(g *graph.Graph, from, to string) bool {
	for _, e := range g.SortedEdges() {
		if e.Type == graph.EdgeDependsOn && e.From == from && e.To == to {
			return true
		}
	}
	return false
}
