package pypi

import (
	"testing"

	"ihbv.io/depsnort/internal/graph"
)

// A minimal pdm.lock: [metadata] with lock_version + groups, packages whose
// dependencies are PEP 508 strings, a transitive chain (requests -> urllib3),
// and a dev-group package. hasEdge/section are shared with uvlock_test.go.
const samplePdmLock = `# This file is @generated by PDM.

[metadata]
groups = ["default", "test"]
lock_version = "4.5.1"
content_hash = "sha256:deadbeef"

[[metadata.targets]]
requires_python = ">=3.10"

[[package]]
name = "urllib3"
version = "2.2.1"
requires_python = ">=3.8"
summary = "HTTP library"
groups = ["default"]
files = [
    {file = "urllib3-2.2.1-py3-none-any.whl", hash = "sha256:aaa"},
]

[[package]]
name = "requests"
version = "2.32.3"
requires_python = ">=3.8"
summary = "HTTP for Humans"
groups = ["default"]
dependencies = [
    "urllib3>=1.21.1,<3",
    "idna>=2.5; python_version < \"3.11\"",
]
files = [
    {file = "requests-2.32.3-py3-none-any.whl", hash = "sha256:bbb"},
]

[[package]]
name = "pytest"
version = "8.2.0"
requires_python = ">=3.8"
summary = "testing framework"
groups = ["test"]
files = [
    {file = "pytest-8.2.0-py3-none-any.whl", hash = "sha256:ccc"},
]
`

func TestParsePdmLock(t *testing.T) {
	g, err := parsePdmLock("app/pdm.lock", []byte(samplePdmLock))
	if err != nil {
		t.Fatalf("parsePdmLock: %v", err)
	}
	if len(g.Roots) != 1 {
		t.Fatalf("roots = %v, want one synthesized root", g.Roots)
	}
	rootID := g.Roots[0]

	for _, want := range []string{
		"pkg:pypi/urllib3@2.2.1", "pkg:pypi/requests@2.32.3", "pkg:pypi/pytest@8.2.0",
	} {
		if g.Get(want) == nil {
			t.Errorf("missing node %s", want)
		}
	}

	// Dependency name extracted from a PEP 508 string: requests -> urllib3.
	if !hasEdge(g, "pkg:pypi/requests@2.32.3", "pkg:pypi/urllib3@2.2.1", graph.EdgeDependsOn) {
		t.Error("missing edge requests -> urllib3 (PEP 508 string parse)")
	}
	// idna is not in the lock -> disclosed as unresolved on requests, not invented.
	if u := g.Get("pkg:pypi/requests@2.32.3").Attr[graph.AttrUnresolved]; u == "" {
		t.Error("expected requests to disclose the unlocked idna dependency")
	}
	// urllib3 reached transitively (real depth), not a flat root edge.
	if d := g.Get("pkg:pypi/urllib3@2.2.1").Depth; d < 2 {
		t.Errorf("urllib3 depth = %d, want >= 2", d)
	}
	if hasEdge(g, rootID, "pkg:pypi/urllib3@2.2.1", graph.EdgeDependsOn) {
		t.Error("urllib3 should be transitive, not a direct root edge")
	}

	// pdm runtime group is "default".
	if s := section(g, "pkg:pypi/requests@2.32.3"); s != "runtime" {
		t.Errorf("requests section = %q, want runtime", s)
	}
	if s := section(g, "pkg:pypi/pytest@8.2.0"); s != "dev:test" {
		t.Errorf("pytest section = %q, want dev:test", s)
	}

	if g.Get(rootID).Attr[graph.AttrFlatResolution] != "" {
		t.Error("pdm.lock must not be marked flat-resolution")
	}
}
