package pypi

import (
	"testing"

	"ihbv.io/depsnort/internal/graph"
)

// A minimal poetry.lock exercising the shapes the reader must handle: registry
// and git sources, a [package.dependencies] sub-table, group membership, and a
// transitive chain (app -> requests -> urllib3) so the in-degree-zero root
// attribution and real depths can be asserted. hasEdge/section are shared with
// uvlock_test.go (same package).
const samplePoetryLock = `# This file is automatically @generated by Poetry 2.4.1 and should not be changed by hand.

[[package]]
name = "urllib3"
version = "2.2.1"
description = "HTTP library"
optional = false
python-versions = ">=3.8"
groups = ["main"]
files = [
    {file = "urllib3-2.2.1-py3-none-any.whl", hash = "sha256:aaa"},
]

[[package]]
name = "requests"
version = "2.32.3"
description = "HTTP for Humans"
optional = false
python-versions = ">=3.8"
groups = ["main"]
files = [
    {file = "requests-2.32.3-py3-none-any.whl", hash = "sha256:bbb"},
]

[package.dependencies]
urllib3 = ">=1.21.1,<3"

[[package]]
name = "pytest"
version = "8.2.0"
description = "testing framework"
optional = false
python-versions = ">=3.8"
groups = ["dev"]
files = [
    {file = "pytest-8.2.0-py3-none-any.whl", hash = "sha256:ccc"},
]

[[package]]
name = "vendored-lib"
version = "0.1.0"
description = "from git"
optional = false
python-versions = ">=3.8"
groups = ["main"]

[package.source]
type = "git"
url = "https://github.com/example/vendored-lib.git"
reference = "HEAD"

[metadata]
lock-version = "2.1"
python-versions = ">=3.10,<4.0"
content-hash = "deadbeef"
`

func TestParsePoetryLock(t *testing.T) {
	g, err := parsePoetryLock("app/poetry.lock", []byte(samplePoetryLock))
	if err != nil {
		t.Fatalf("parsePoetryLock: %v", err)
	}

	// A root was synthesized (poetry.lock carries none) and named after the dir.
	if len(g.Roots) != 1 {
		t.Fatalf("roots = %v, want exactly one synthesized root", g.Roots)
	}
	rootID := g.Roots[0]
	if a := g.Get(rootID).Attr["pypi.direct_attribution"]; a != "in-degree-zero" {
		t.Errorf("root direct_attribution = %q, want in-degree-zero", a)
	}

	for _, want := range []string{
		"pkg:pypi/urllib3@2.2.1", "pkg:pypi/requests@2.32.3",
		"pkg:pypi/pytest@8.2.0", "pkg:pypi/vendored-lib@0.1.0",
	} {
		if g.Get(want) == nil {
			t.Errorf("missing node %s", want)
		}
	}

	// Transitive edge from [package.dependencies]: requests -> urllib3.
	if !hasEdge(g, "pkg:pypi/requests@2.32.3", "pkg:pypi/urllib3@2.2.1", graph.EdgeDependsOn) {
		t.Error("missing transitive edge requests -> urllib3")
	}
	// urllib3 is depended upon, so it is NOT a direct root edge...
	if hasEdge(g, rootID, "pkg:pypi/urllib3@2.2.1", graph.EdgeDependsOn) {
		t.Error("urllib3 should be reached transitively, not attached to root")
	}
	// ...while requests (in-degree zero) IS.
	if !hasEdge(g, rootID, "pkg:pypi/requests@2.32.3", graph.EdgeDependsOn) {
		t.Error("requests (in-degree zero) should be a direct root edge")
	}

	// urllib3 sits below requests: real depth, not flat.
	if d := g.Get("pkg:pypi/urllib3@2.2.1").Depth; d < 2 {
		t.Errorf("urllib3 depth = %d, want >= 2", d)
	}

	// Group -> section tagging.
	if s := section(g, "pkg:pypi/requests@2.32.3"); s != "runtime" {
		t.Errorf("requests section = %q, want runtime", s)
	}
	if s := section(g, "pkg:pypi/pytest@8.2.0"); s != "dev:dev" {
		t.Errorf("pytest section = %q, want dev:dev", s)
	}

	// Source provenance: registry default vs git.
	if cls, _ := g.Get("pkg:pypi/requests@2.32.3").SourceOf(); cls != graph.SourceRegistry {
		t.Errorf("requests source = %q, want registry", cls)
	}
	if cls, ref := g.Get("pkg:pypi/vendored-lib@0.1.0").SourceOf(); cls != graph.SourceGit || ref == "" {
		t.Errorf("vendored-lib source = (%q,%q), want git with url", cls, ref)
	}

	// No flat-resolution penalty: poetry.lock expresses edges.
	if g.Get(rootID).Attr[graph.AttrFlatResolution] != "" {
		t.Error("poetry.lock must not be marked flat-resolution")
	}
}
