package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// D-149: the cargo build.rs fetch was opt-in (-cargo-fetch-source, D-140) on a
// premise D-141 corrected — PyPI already fetches per-dependency source by
// default. The owner's ruling: coverage defaults on, flags are for opting out,
// unless the action itself carries a risk worth weighing; this fetch is
// checksum-verified, executes nothing, and talks to a registry other default
// stages already use, so it carries none. These tests run -offline so the
// client serves only its (empty) cache — hermetic, while the data_sources
// entry still records that the enrichment RAN and what it could not serve.

func d149CargoProject(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	lock := `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "coldapp"
version = "0.1.0"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.188"
source = "registry+https://github.com/rust-lang/crates.io-index"
`
	if err := os.WriteFile(filepath.Join(dir, "Cargo.lock"), []byte(lock), 0o644); err != nil {
		t.Fatal(err)
	}
	return dir
}

// d149Scan mirrors runScan but keeps the registry stage: the cargo-source
// enrichment nests inside it (opting out of registries opts out of registry
// fetches), and -offline keeps that whole stage cache-only and hermetic.
func d149Scan(t *testing.T, args ...string) map[string]any {
	t.Helper()
	out := filepath.Join(t.TempDir(), "report.json")
	full := append([]string{"scan", "-no-osv", "-offline", "-o", out}, args...)
	if code := run(full); code != 0 {
		t.Fatalf("scan exited %d", code)
	}
	raw, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	var doc map[string]any
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	return doc
}

func d149DataSources(t *testing.T, doc map[string]any) map[string]bool {
	t.Helper()
	out := map[string]bool{}
	list, _ := doc["data_sources"].([]any)
	for _, e := range list {
		if m, ok := e.(map[string]any); ok {
			if name, _ := m["name"].(string); name != "" {
				out[name] = true
			}
		}
	}
	return out
}

// TestD149CargoSourceFetchIsDefaultOn: with no flag at all, the enrichment runs
// for the source-unavailable crate and reports itself as a data source.
func TestD149CargoSourceFetchIsDefaultOn(t *testing.T) {
	dir := d149CargoProject(t)
	doc := d149Scan(t, dir)
	if !d149DataSources(t, doc)["cargo-source"] {
		t.Fatalf("cargo-source should run by default; data sources: %v", d149DataSources(t, doc))
	}
}

// TestD149OptOutFlagStopsTheFetch: -no-cargo-fetch-source is the escape hatch,
// and the unexamined crate stays disclosed rather than quietly dropped.
func TestD149OptOutFlagStopsTheFetch(t *testing.T) {
	dir := d149CargoProject(t)
	doc := d149Scan(t, "-no-cargo-fetch-source", dir)
	if d149DataSources(t, doc)["cargo-source"] {
		t.Fatal("-no-cargo-fetch-source must stop the enrichment")
	}
	cov := coverageOf(t, doc)
	if gaps, _ := cov["install_surface_gaps"].(float64); gaps == 0 {
		t.Errorf("the unexamined crate must stay disclosed: %v", cov)
	}
}
