# frozen_string_literal: true
source 'https://rubygems.org'
ruby '3.2.2'

gem 'rails', '~> 7.0'
gem 'puma', '>= 5.0', '< 6.0'
gem 'pg'
gem "redis", require: false
gem 'nokogiri', github: 'sparklemotion/nokogiri' # native ext

group :development, :test do
  gem 'rspec-rails', '~> 6.0'
end

gemspec
